-- this script updates the tables TASKANA_SCHEMA_VERSION and TASK.

SET SCHEMA %schemaName%;

INSERT INTO TASKANA_SCHEMA_VERSION (VERSION, CREATED) VALUES ('5.0.0', CURRENT_TIMESTAMP);

ALTER TABLE ATTACHMENT ADD COLUMN RECEIVED TIMESTAMP NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE TASK');
