CREATE SCHEMA IF NOT EXISTS KADAI;
CREATE SCHEMA IF NOT EXISTS CUSTOMDB;
CREATE TABLE IF NOT EXISTS CUSTOMDB.TEST (
        ID CHAR(40) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID)
);
SET SCHEMA KADAI;
