-- the order is important!
DELETE FROM TASK_COMMENT;
DELETE FROM CONFIGURATION;
DELETE FROM TASK_HISTORY_EVENT;
DELETE FROM WORKBASKET_HISTORY_EVENT;
DELETE FROM CLASSIFICATION_HISTORY_EVENT;
DELETE FROM ATTACHMENT;
DELETE FROM TASK;
DELETE FROM WORKBASKET_ACCESS_LIST;
DELETE FROM WORKBASKET;
DELETE FROM DISTRIBUTION_TARGETS;
DELETE FROM CLASSIFICATION;
DELETE FROM OBJECT_REFERENCE;
DELETE FROM SCHEDULED_JOB;
DELETE FROM USER_INFO;
COMMIT;
