ALTER SESSION SET CURRENT_SCHEMA = %schemaName%;

CREATE SEQUENCE TASKANA_SCHEMA_VERSION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
CREATE TABLE TASKANA_SCHEMA_VERSION (
    ID NUMBER(10) NOT NULL,
    VERSION VARCHAR2(255) NOT NULL,
    CREATED TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    CONSTRAINT TASKANA_SCHEMA_VERSION_PKEY PRIMARY KEY (ID)
);
-- The VERSION value must match the value of TaskanaEngineConfiguration.TASKANA_SCHEMA_VERSION
INSERT INTO TASKANA_SCHEMA_VERSION (ID, VERSION, CREATED) VALUES (TASKANA_SCHEMA_VERSION_ID_SEQ.NEXTVAL, '4.0.0', CURRENT_TIMESTAMP);

CREATE TABLE CLASSIFICATION (
    ID VARCHAR2(40) NOT NULL,
    KEY VARCHAR2(32) NOT NULL,
    PARENT_ID VARCHAR2(40) NULL,
    PARENT_KEY VARCHAR2(32) NULL,
    CATEGORY VARCHAR2(32),
    TYPE VARCHAR2(32),
    DOMAIN VARCHAR2(255) NULL,
    VALID_IN_DOMAIN NUMBER(1) NOT NULL CHECK  (VALID_IN_DOMAIN IN (0,1)),
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    MODIFIED TIMESTAMP WITH LOCAL TIME ZONE,
    NAME VARCHAR2(255),
    DESCRIPTION VARCHAR2(255),
    PRIORITY NUMBER(38) NOT NULL,
    SERVICE_LEVEL VARCHAR2(255),
    APPLICATION_ENTRY_POINT VARCHAR2(255),
    CUSTOM_1 VARCHAR2(255),
    CUSTOM_2 VARCHAR2(255),
    CUSTOM_3 VARCHAR2(255),
    CUSTOM_4 VARCHAR2(255),
    CUSTOM_5 VARCHAR2(255),
    CUSTOM_6 VARCHAR2(255),
    CUSTOM_7 VARCHAR2(255),
    CUSTOM_8 VARCHAR2(255),
    CONSTRAINT CLASSIFICATION_PKEY PRIMARY KEY (ID),
    CONSTRAINT UC_CLASS_KEY_DOMAIN UNIQUE (KEY, DOMAIN)
);

CREATE TABLE WORKBASKET (
    ID VARCHAR2(40) NOT NULL,
    KEY VARCHAR2(64) NOT NULL,
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    MODIFIED TIMESTAMP WITH LOCAL TIME ZONE,
    NAME VARCHAR2(255) NOT NULL,
    DOMAIN VARCHAR2(32) NOT NULL,
    TYPE VARCHAR2(16) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    OWNER VARCHAR2(128),
    CUSTOM_1 VARCHAR2(255),
    CUSTOM_2 VARCHAR2(255),
    CUSTOM_3 VARCHAR2(255),
    CUSTOM_4 VARCHAR2(255),
    ORG_LEVEL_1 VARCHAR2(255),
    ORG_LEVEL_2 VARCHAR2(255),
    ORG_LEVEL_3 VARCHAR2(255),
    ORG_LEVEL_4 VARCHAR2(255),
    MARKED_FOR_DELETION NUMBER(1) NOT NULL CHECK  (MARKED_FOR_DELETION IN (0,1)),
    CONSTRAINT WORKBASKET_PKEY PRIMARY KEY (ID),
    CONSTRAINT WB_KEY_DOMAIN UNIQUE (KEY, DOMAIN)
);


CREATE TABLE TASK (
    ID VARCHAR2(40) NOT NULL,
    EXTERNAL_ID VARCHAR2(64) NOT NULL,
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    CLAIMED TIMESTAMP WITH LOCAL TIME ZONE,
    COMPLETED TIMESTAMP WITH LOCAL TIME ZONE,
    MODIFIED TIMESTAMP WITH LOCAL TIME ZONE,
    PLANNED TIMESTAMP WITH LOCAL TIME ZONE,
    DUE TIMESTAMP WITH LOCAL TIME ZONE,
    NAME VARCHAR2(255),
    CREATOR VARCHAR2(32),
    DESCRIPTION VARCHAR2(1024),
    NOTE VARCHAR2(4000),
    PRIORITY NUMBER(10),
    STATE VARCHAR2(20),
    CLASSIFICATION_CATEGORY VARCHAR2(32),
    CLASSIFICATION_KEY VARCHAR2(32),
    CLASSIFICATION_ID VARCHAR2(40),
    WORKBASKET_ID VARCHAR2(40),
    WORKBASKET_KEY VARCHAR2(64),
    DOMAIN VARCHAR2(32),
    BUSINESS_PROCESS_ID VARCHAR2(128),
    PARENT_BUSINESS_PROCESS_ID VARCHAR2(128),
    OWNER VARCHAR2(32),
    POR_COMPANY VARCHAR2(32) NOT NULL,
    POR_SYSTEM VARCHAR2(32),
    POR_INSTANCE VARCHAR2(32),
    POR_TYPE VARCHAR2(32) NOT NULL,
    POR_VALUE VARCHAR2(128) NOT NULL,
    IS_READ CHAR(1) NOT NULL,
    IS_TRANSFERRED CHAR(1) NOT NULL,
    CALLBACK_INFO CLOB,
    CALLBACK_STATE VARCHAR2(30),
    CUSTOM_ATTRIBUTES CLOB,
    CUSTOM_1 VARCHAR2(255),
    CUSTOM_2 VARCHAR2(255),
    CUSTOM_3 VARCHAR2(255),
    CUSTOM_4 VARCHAR2(255),
    CUSTOM_5 VARCHAR2(255),
    CUSTOM_6 VARCHAR2(255),
    CUSTOM_7 VARCHAR2(255),
    CUSTOM_8 VARCHAR2(255),
    CUSTOM_9 VARCHAR2(255),
    CUSTOM_10 VARCHAR2(255),
    CUSTOM_11 VARCHAR2(255),
    CUSTOM_12 VARCHAR2(255),
    CUSTOM_13 VARCHAR2(255),
    CUSTOM_14 VARCHAR2(255),
    CUSTOM_15 VARCHAR2(255),
    CUSTOM_16 VARCHAR2(255),
    CONSTRAINT TASK_PKEY PRIMARY KEY (ID),
    CONSTRAINT UC_EXTERNAL_ID UNIQUE (EXTERNAL_ID),
    CONSTRAINT TASK_CLASS FOREIGN KEY (CLASSIFICATION_ID) REFERENCES CLASSIFICATION(ID),
    CONSTRAINT TASK_WB FOREIGN KEY (WORKBASKET_ID) REFERENCES WORKBASKET(ID)
);


CREATE TABLE DISTRIBUTION_TARGETS (
    SOURCE_ID VARCHAR2(40) NOT NULL,
    TARGET_ID VARCHAR2(40) NOT NULL,
    CONSTRAINT DISTRIBUTION_TARGETS_PKEY PRIMARY KEY (SOURCE_ID, TARGET_ID)
);

CREATE TABLE WORKBASKET_ACCESS_LIST (
    ID VARCHAR2(40) NOT NULL,
    WORKBASKET_ID VARCHAR2(40) NOT NULL,
    ACCESS_ID VARCHAR2(255) NOT NULL,
    ACCESS_NAME VARCHAR2(255),
    PERM_READ CHAR(1) NOT NULL,
    PERM_OPEN CHAR(1) NOT NULL,
    PERM_APPEND CHAR(1) NOT NULL,
    PERM_TRANSFER CHAR(1) NOT NULL,
    PERM_DISTRIBUTE CHAR(1) NOT NULL,
    PERM_CUSTOM_1 CHAR(1) NOT NULL,
    PERM_CUSTOM_2 CHAR(1) NOT NULL,
    PERM_CUSTOM_3 CHAR(1) NOT NULL,
    PERM_CUSTOM_4 CHAR(1) NOT NULL,
    PERM_CUSTOM_5 CHAR(1) NOT NULL,
    PERM_CUSTOM_6 CHAR(1) NOT NULL,
    PERM_CUSTOM_7 CHAR(1) NOT NULL,
    PERM_CUSTOM_8 CHAR(1) NOT NULL,
    PERM_CUSTOM_9 CHAR(1) NOT NULL,
    PERM_CUSTOM_10 CHAR(1) NOT NULL,
    PERM_CUSTOM_11 CHAR(1) NOT NULL,
    PERM_CUSTOM_12 CHAR(1) NOT NULL,
    CONSTRAINT WORKBASKET_ACCESS_LIST_PKEY PRIMARY KEY (ID),
    CONSTRAINT UC_ACCESSID_WBID UNIQUE (ACCESS_ID, WORKBASKET_ID),
    CONSTRAINT ACCESS_LIST_WB FOREIGN KEY (WORKBASKET_ID) REFERENCES WORKBASKET(ID) ON DELETE CASCADE
);


CREATE TABLE OBJECT_REFERENCE (
    ID VARCHAR2(40) NOT NULL,
    COMPANY VARCHAR2(32) NOT NULL,
    SYSTEM VARCHAR2(32),
    SYSTEM_INSTANCE VARCHAR2(32),
    TYPE VARCHAR2(32) NOT NULL,
    VALUE VARCHAR2(128) NOT NULL,
    CONSTRAINT OBJECT_REFERENCE_PKEY PRIMARY KEY (ID)
);


CREATE TABLE ATTACHMENT (
    ID VARCHAR2(40) NOT NULL,
    TASK_ID VARCHAR2(40) NOT NULL,
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    MODIFIED TIMESTAMP WITH LOCAL TIME ZONE ,
    CLASSIFICATION_KEY VARCHAR2(32),
    CLASSIFICATION_ID VARCHAR2(40),
    REF_COMPANY VARCHAR2(32) NOT NULL,
    REF_SYSTEM VARCHAR2(32) NOT NULL,
    REF_INSTANCE VARCHAR2(32) NOT NULL,
    REF_TYPE VARCHAR2(32) NOT NULL,
    REF_VALUE VARCHAR2(128) NOT NULL,
    CHANNEL VARCHAR2(64),
    RECEIVED TIMESTAMP WITH LOCAL TIME ZONE,
    CUSTOM_ATTRIBUTES CLOB,
    CONSTRAINT ATTACHMENT_PKEY PRIMARY KEY (ID),
    CONSTRAINT ATT_CLASS FOREIGN KEY (CLASSIFICATION_ID) REFERENCES CLASSIFICATION(ID)
);


CREATE TABLE TASK_COMMENT (
    ID VARCHAR2(40) NOT NULL,
    TASK_ID VARCHAR2(40) NOT NULL,
    TEXT_FIELD VARCHAR2(1024),
    CREATOR VARCHAR2(32),
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    MODIFIED TIMESTAMP WITH LOCAL TIME ZONE,
    CONSTRAINT TASK_COMMENT_PKEY PRIMARY KEY (ID),
    CONSTRAINT COMMENT_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID) ON DELETE CASCADE
);


CREATE TABLE SCHEDULED_JOB (
    JOB_ID NUMBER(10) NOT NULL,
    PRIORITY NUMBER(10),
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    DUE TIMESTAMP WITH LOCAL TIME ZONE,
    STATE VARCHAR2(32),
    LOCKED_BY VARCHAR2(32),
    LOCK_EXPIRES TIMESTAMP WITH LOCAL TIME ZONE,
    TYPE VARCHAR2(32),
    RETRY_COUNT NUMBER(10) NOT NULL,
    ARGUMENTS CLOB,
    CONSTRAINT SCHEDULED_JOB_PKEY PRIMARY KEY (JOB_ID)
);


CREATE TABLE TASK_HISTORY_EVENT (
    ID VARCHAR2(40) NOT NULL,
    BUSINESS_PROCESS_ID VARCHAR2(128),
    PARENT_BUSINESS_PROCESS_ID VARCHAR2(128),
    TASK_ID VARCHAR2(40),
    EVENT_TYPE VARCHAR2(32),
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    USER_ID VARCHAR2(32),
    DOMAIN VARCHAR2(32),
    WORKBASKET_KEY VARCHAR2(64),
    POR_COMPANY VARCHAR2(32),
    POR_SYSTEM VARCHAR2(32),
    POR_INSTANCE VARCHAR2(32),
    POR_TYPE VARCHAR2(32),
    POR_VALUE VARCHAR2(128),
    TASK_CLASSIFICATION_KEY VARCHAR2(32),
    TASK_CLASSIFICATION_CATEGORY VARCHAR2(32),
    ATTACHMENT_CLASSIFICATION_KEY VARCHAR2(32),
    OLD_VALUE VARCHAR2(255),
    NEW_VALUE VARCHAR2(255),
    CUSTOM_1 VARCHAR2(128),
    CUSTOM_2 VARCHAR2(128),
    CUSTOM_3 VARCHAR2(128),
    CUSTOM_4 VARCHAR2(128),
    DETAILS CLOB,
    CONSTRAINT TASK_HISTORY_EVENT_PKEY PRIMARY KEY (ID)
);


CREATE TABLE WORKBASKET_HISTORY_EVENT (
    ID VARCHAR2(40) NOT NULL,
    WORKBASKET_ID VARCHAR2(40),
    EVENT_TYPE VARCHAR2(40),
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    USER_ID VARCHAR2(32),
    DOMAIN VARCHAR2(32),
    KEY VARCHAR2(64),
    TYPE VARCHAR2(64),
    OWNER VARCHAR2(128),
    CUSTOM_1 VARCHAR2(255),
    CUSTOM_2 VARCHAR2(255),
    CUSTOM_3 VARCHAR2(255),
    CUSTOM_4 VARCHAR2(255),
    ORGLEVEL_1 VARCHAR2(255),
    ORGLEVEL_2 VARCHAR2(255),
    ORGLEVEL_3 VARCHAR2(255),
    ORGLEVEL_4 VARCHAR2(255),
    DETAILS VARCHAR2(4000),
    CONSTRAINT WORKBASKET_HISTORY_EVENT_PKEY PRIMARY KEY (ID)
);


CREATE TABLE CLASSIFICATION_HISTORY_EVENT (
    ID VARCHAR2(40) NOT NULL,
    EVENT_TYPE VARCHAR2(40),
    CREATED TIMESTAMP WITH LOCAL TIME ZONE,
    USER_ID VARCHAR2(32),
    CLASSIFICATION_ID VARCHAR2(40),
    APPLICATION_ENTRY_POINT VARCHAR2(255),
    CATEGORY VARCHAR2(64),
    DOMAIN VARCHAR2(32),
    KEY VARCHAR2(40),
    NAME VARCHAR2(255),
    PARENT_ID VARCHAR2(40) NOT NULL,
    PARENT_KEY VARCHAR2(32) NOT NULL,
    PRIORITY NUMBER(38) NOT NULL,
    SERVICE_LEVEL VARCHAR2(255),
    TYPE VARCHAR2(32),
    CUSTOM_1 VARCHAR2(255),
    CUSTOM_2 VARCHAR2(255),
    CUSTOM_3 VARCHAR2(255),
    CUSTOM_4 VARCHAR2(255),
    CUSTOM_5 VARCHAR2(255),
    CUSTOM_6 VARCHAR2(255),
    CUSTOM_7 VARCHAR2(255),
    CUSTOM_8 VARCHAR2(255),
    DETAILS VARCHAR2(4000),
    CONSTRAINT CLASSIFICATION_HISTORY_EVENT_PKEY PRIMARY KEY (ID)
);



CREATE TABLE CONFIGURATION (
    ENFORCE_SECURITY CHAR(1) NOT NULL
);



CREATE SEQUENCE SCHEDULED_JOB_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
