-- this script updates the TASKANA_HISTORY_EVENT table.

SET SCHEMA %schemaName%;

ALTER TABLE TASK_HISTORY_EVENT ALTER COLUMN CUSTOM_1 SET DATA TYPE VARCHAR(255) ALTER COLUMN CUSTOM_2 SET DATA TYPE VARCHAR(255) ALTER COLUMN CUSTOM_3 SET DATA TYPE VARCHAR(255) ALTER COLUMN CUSTOM_4 SET DATA TYPE VARCHAR(255);
CALL SYSPROC.ADMIN_CMD ( 'REORG TABLE TASK_HISTORY_EVENT allow read access' );
