-- this script update the tables TASKANA_SCHEMA_VERSION and TIMESTAMP columns.

SET SCHEMA %schemaName%;

ALTER TABLE TASKANA_SCHEMA_VERSION ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);
INSERT INTO TASKANA_SCHEMA_VERSION (VERSION, CREATED) VALUES ('4.0.0', CURRENT_TIMESTAMP);

ALTER TABLE CLASSIFICATION ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE CLASSIFICATION ALTER COLUMN MODIFIED SET DATA TYPE TIMESTAMP(9);

ALTER TABLE WORKBASKET ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE WORKBASKET ALTER COLUMN MODIFIED SET DATA TYPE TIMESTAMP(9);

ALTER TABLE TASK ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK ALTER COLUMN CLAIMED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK ALTER COLUMN COMPLETED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK ALTER COLUMN MODIFIED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK ALTER COLUMN PLANNED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK ALTER COLUMN DUE SET DATA TYPE TIMESTAMP(9);

ALTER TABLE ATTACHMENT ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE ATTACHMENT ALTER COLUMN MODIFIED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE ATTACHMENT ALTER COLUMN RECEIVED SET DATA TYPE TIMESTAMP(9);

ALTER TABLE TASK_COMMENT ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK_COMMENT ALTER COLUMN MODIFIED SET DATA TYPE TIMESTAMP(9);

ALTER TABLE SCHEDULED_JOB ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE SCHEDULED_JOB ALTER COLUMN DUE SET DATA TYPE TIMESTAMP(9);
ALTER TABLE SCHEDULED_JOB ALTER COLUMN LOCK_EXPIRES SET DATA TYPE TIMESTAMP(9);

ALTER TABLE TASK_HISTORY_EVENT ALTER COLUMN CREATED SET DATA TYPE TIMESTAMP(9);

ALTER TABLE WORKBASKET_HISTORY_EVENT ALTER COLUMN DUE SET DATA TYPE TIMESTAMP(9);

ALTER TABLE CLASSIFICATION_HISTORY_EVENT ALTER COLUMN LOCK_EXPIRES SET DATA TYPE TIMESTAMP(9);
