INSERT INTO CLASSIFICATION VALUES ('1', 'NT', '', 'EXTERN', 'BRIEF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ROOT', 'DESC', 1, 'P1D');
INSERT INTO CLASSIFICATION VALUES ('2', 'NT', '1','MANUELL', 'BRIEF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'CHILD', 'DESC', 1, 'P1D');
INSERT INTO CLASSIFICATION VALUES ('3', 'NT', '1','MASCHINELL', 'BRIEF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ANOTHER CHILD', 'DESC', 1, 'P2D');
INSERT INTO CLASSIFICATION VALUES ('4', 'NT', '2','PROZESS', 'EXCEL-SHEET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'GRANDCHILD', 'DESC', 1, 'P1DT4H12S');

INSERT INTO CLASSIFICATION VALUES('13', 'NT', '3', 'MANUELL', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ANOTHER GRANDCHILD', 'DESC', 3, 'P3DT12H');
INSERT INTO CLASSIFICATION VALUES('14', 'NT', '4', 'MANUELL', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'BIG GRANDCHILD', 'DESC', 2, 'P2DT12H');
INSERT INTO CLASSIFICATION VALUES('15', 'NT', '3', 'PROZESS', 'MINDMAP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SMALL GRANDCHILD', 'DESC', 4, 'P5DT12H');
INSERT INTO CLASSIFICATION VALUES('16', 'NT', '4', 'MANUELL', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'NO GRANDCHILD', 'DESC', 3, 'P3DT');
