CREATE SCHEMA IF NOT EXISTS TASKANA;
CREATE SCHEMA IF NOT EXISTS GESCHBUCH;
CREATE TABLE IF NOT EXISTS GESCHBUCH.TEST (
	ID CHAR(40) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);
SET SCHEMA TASKANA;