package pro.taskana.monitor.internal;

import java.time.Instant;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Select;

import pro.taskana.monitor.api.CombinedClassificationFilter;
import pro.taskana.monitor.api.SelectedItem;
import pro.taskana.monitor.api.TaskTimestamp;
import pro.taskana.monitor.api.reports.TimeIntervalReportBuilder;
import pro.taskana.monitor.api.reports.item.DetailedMonitorQueryItem;
import pro.taskana.monitor.api.reports.item.MonitorQueryItem;
import pro.taskana.monitor.api.reports.item.TaskQueryItem;
import pro.taskana.monitor.api.reports.item.TimestampQueryItem;
import pro.taskana.task.api.TaskCustomField;
import pro.taskana.task.api.TaskState;

/** This class is the mybatis mapping of task monitoring. */
@SuppressWarnings({"checkstyle:LineLength", "checkstyle:Indentation"})
public interface MonitorMapper {

  @Select(
      "<script>"
          + "SELECT B.WORKBASKET_KEY, B.AGE_IN_DAYS, COUNT(B.AGE_IN_DAYS) AS NUMBER_OF_TASKS FROM ("
          + "<if test=\"_databaseId == 'db2'\">SELECT T.WORKBASKET_KEY, (DAYS(T.${timestamp}) - DAYS(CAST(#{now} as TIMESTAMP))) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'h2'\">SELECT T.WORKBASKET_KEY, DATEDIFF('DAY', #{now}, T.${timestamp}) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'postgres'\">SELECT T.WORKBASKET_KEY, DATE_PART('DAY', T.${timestamp} - #{now}) as AGE_IN_DAYS </if> "
          + "FROM TASK AS T LEFT JOIN ATTACHMENT AS A ON T.ID = A.TASK_ID "
          + "<where>"
          + "<if test=\"report.workbasketIds != null\">"
          + "T.WORKBASKET_ID IN (<foreach collection='report.workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test=\"report.states != null\">"
          + "AND T.STATE IN (<foreach collection='report.states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test=\"report.classificationCategory != null\">"
          + "AND T.CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test=\"report.domains != null\">"
          + "AND T.DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND T.CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND T.CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "<if test=\"report.combinedClassificationFilter != null\">"
          + "AND <foreach collection='report.combinedClassificationFilter' item='item' separator='OR'> "
          + "T.CLASSIFICATION_ID = #{item.taskClassificationId}"
          + "<if test=\"item.attachmentClassificationId != null\">"
          + "AND A.CLASSIFICATION_ID = #{item.attachmentClassificationId}"
          + "</if>"
          + "</foreach>"
          + "</if>"
          + "AND T.${timestamp} IS NOT NULL "
          + "</where>"
          + ") AS B "
          + "GROUP BY B.WORKBASKET_KEY, B.AGE_IN_DAYS"
          + "</script>")
  @Result(column = "WORKBASKET_KEY", property = "key")
  @Result(column = "AGE_IN_DAYS", property = "ageInDays")
  @Result(column = "NUMBER_OF_TASKS", property = "numberOfTasks")
  List<MonitorQueryItem> getTaskCountOfWorkbaskets(
      @Param("now") Instant now,
      @Param("timestamp") TaskTimestamp timestamp,
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report);

  @Select(
      "<script>"
          + "SELECT B.CLASSIFICATION_CATEGORY, B.AGE_IN_DAYS, COUNT(B.AGE_IN_DAYS) AS NUMBER_OF_TASKS FROM ("
          + "<if test=\"_databaseId == 'db2'\">SELECT CLASSIFICATION_CATEGORY, (DAYS(${timestamp}) - DAYS(CAST(#{now} as TIMESTAMP))) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'h2'\">SELECT CLASSIFICATION_CATEGORY, DATEDIFF('DAY', #{now}, ${timestamp}) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'postgres'\">SELECT CLASSIFICATION_CATEGORY, DATE_PART('DAY', ${timestamp} - #{now}) as AGE_IN_DAYS </if> "
          + "FROM TASK T "
          + "<where>"
          + "<if test=\"report.workbasketIds != null\">"
          + "WORKBASKET_ID IN (<foreach collection='report.workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test=\"report.states != null\">"
          + "AND STATE IN (<foreach collection='report.states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test=\"report.classificationCategory != null\">"
          + "AND CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test=\"report.domains != null\">"
          + "AND DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "AND ${timestamp} IS NOT NULL "
          + "</where>"
          + ") AS B "
          + "GROUP BY B.CLASSIFICATION_CATEGORY, B.AGE_IN_DAYS "
          + "</script>")
  @Result(column = "CLASSIFICATION_CATEGORY", property = "key")
  @Result(column = "AGE_IN_DAYS", property = "ageInDays")
  @Result(column = "NUMBER_OF_TASKS", property = "numberOfTasks")
  List<MonitorQueryItem> getTaskCountOfCategories(
      @Param("now") Instant now,
      @Param("timestamp") TaskTimestamp timestamp,
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report);

  @Select(
      "<script>"
          + "SELECT B.CLASSIFICATION_KEY, B.AGE_IN_DAYS, COUNT(B.AGE_IN_DAYS) AS NUMBER_OF_TASKS FROM ("
          + "<if test=\"_databaseId == 'db2'\">SELECT CLASSIFICATION_KEY, (DAYS(${timestamp}) - DAYS(CAST(#{now} as TIMESTAMP))) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'h2'\">SELECT CLASSIFICATION_KEY, DATEDIFF('DAY', #{now}, ${timestamp}) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'postgres'\">SELECT CLASSIFICATION_KEY, DATE_PART('DAY', ${timestamp} - #{now}) as AGE_IN_DAYS </if> "
          + "FROM TASK T "
          + "<where>"
          + "<if test=\"report.workbasketIds != null\">"
          + "WORKBASKET_ID IN (<foreach collection='report.workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test=\"report.states != null\">"
          + "AND STATE IN (<foreach collection='report.states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test=\"report.classificationCategory != null\">"
          + "AND CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test=\"report.domains != null\">"
          + "AND DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "AND ${timestamp} IS NOT NULL "
          + "</where>"
          + ") AS B "
          + "GROUP BY B.CLASSIFICATION_KEY, B.AGE_IN_DAYS "
          + "</script>")
  @Result(column = "CLASSIFICATION_KEY", property = "key")
  @Result(column = "AGE_IN_DAYS", property = "ageInDays")
  @Result(column = "NUMBER_OF_TASKS", property = "numberOfTasks")
  List<MonitorQueryItem> getTaskCountOfClassifications(
      @Param("now") Instant now,
      @Param("timestamp") TaskTimestamp timestamp,
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report);

  @Select(
      "<script>"
          + "SELECT B.TASK_CLASSIFICATION_KEY, B.ATTACHMENT_CLASSIFICATION_KEY, B.AGE_IN_DAYS, COUNT(B.AGE_IN_DAYS) AS NUMBER_OF_TASKS FROM ("
          + "<if test=\"_databaseId == 'db2'\">SELECT T.CLASSIFICATION_KEY as TASK_CLASSIFICATION_KEY, A.CLASSIFICATION_KEY as ATTACHMENT_CLASSIFICATION_KEY, (DAYS(T.${timestamp}) - DAYS(CAST(#{now} as TIMESTAMP))) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'h2'\">SELECT T.CLASSIFICATION_KEY as TASK_CLASSIFICATION_KEY, A.CLASSIFICATION_KEY as ATTACHMENT_CLASSIFICATION_KEY, DATEDIFF('DAY', #{now}, T.${timestamp}) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'postgres'\">SELECT T.CLASSIFICATION_KEY as TASK_CLASSIFICATION_KEY, A.CLASSIFICATION_KEY as ATTACHMENT_CLASSIFICATION_KEY, DATE_PART('DAY', T.${timestamp} - #{now}) as AGE_IN_DAYS </if> "
          + "FROM TASK AS T LEFT JOIN ATTACHMENT AS A ON T.ID = A.TASK_ID "
          + "<where>"
          + "<if test=\"report.workbasketIds != null\">"
          + "T.WORKBASKET_ID IN (<foreach collection='report.workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test=\"report.states != null\">"
          + "AND STATE IN (<foreach collection='report.states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test=\"report.classificationCategory != null\">"
          + "AND CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test=\"report.domains != null\">"
          + "AND DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND T.CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND T.CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "AND T.${timestamp} IS NOT NULL "
          + "</where>"
          + ") AS B "
          + "GROUP BY B.TASK_CLASSIFICATION_KEY, B.ATTACHMENT_CLASSIFICATION_KEY, B.AGE_IN_DAYS "
          + "</script>")
  @Result(column = "TASK_CLASSIFICATION_KEY", property = "key")
  @Result(column = "ATTACHMENT_CLASSIFICATION_KEY", property = "attachmentKey")
  @Result(column = "AGE_IN_DAYS", property = "ageInDays")
  @Result(column = "NUMBER_OF_TASKS", property = "numberOfTasks")
  List<DetailedMonitorQueryItem> getTaskCountOfDetailedClassifications(
      @Param("now") Instant now,
      @Param("timestamp") TaskTimestamp timestamp,
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report);

  @Select(
      "<script>"
          + "SELECT B.CUSTOM_FIELD, B.AGE_IN_DAYS, COUNT(B.AGE_IN_DAYS) AS NUMBER_OF_TASKS FROM ("
          + "<if test=\"_databaseId == 'db2'\">SELECT ${report.taskCustomField} as CUSTOM_FIELD, (DAYS(${timestamp}) - DAYS(CAST(#{now} as TIMESTAMP))) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'h2'\">SELECT ${report.taskCustomField} as CUSTOM_FIELD, DATEDIFF('DAY', #{now}, ${timestamp}) as AGE_IN_DAYS </if> "
          + "<if test=\"_databaseId == 'postgres'\">SELECT ${report.taskCustomField} as CUSTOM_FIELD, DATE_PART('DAY', ${timestamp} - #{now}) as AGE_IN_DAYS </if> "
          + "FROM TASK T "
          + "<where>"
          + "<if test=\"report.workbasketIds != null\">"
          + "WORKBASKET_ID IN (<foreach collection='report.workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test=\"report.states != null\">"
          + "AND STATE IN (<foreach collection='report.states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test=\"report.classificationCategory != null\">"
          + "AND CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test=\"report.domains != null\">"
          + "AND DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "AND ${timestamp} IS NOT NULL "
          + "</where>"
          + ") AS B "
          + "GROUP BY B.CUSTOM_FIELD, B.AGE_IN_DAYS "
          + "</script>")
  @Result(column = "CUSTOM_FIELD", property = "key")
  @Result(column = "AGE_IN_DAYS", property = "ageInDays")
  @Result(column = "NUMBER_OF_TASKS", property = "numberOfTasks")
  List<MonitorQueryItem> getTaskCountOfTaskCustomFieldValues(
      @Param("now") Instant now,
      @Param("timestamp") TaskTimestamp timestamp,
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report);

  @Select(
      "<script>"
          + "SELECT T.ID FROM TASK T "
          + "<if test=\"joinWithAttachments\">"
          + "LEFT JOIN ATTACHMENT A ON T.ID = A.TASK_ID "
          + "</if>"
          + "<where>"
          + "<if test=\"report.workbasketIds != null\">"
          + "T.WORKBASKET_ID IN (<foreach collection='report.workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test=\"report.states != null\">"
          + "AND T.STATE IN (<foreach collection='report.states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test=\"report.classificationCategory != null\">"
          + "AND T.CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test=\"report.domains != null\">"
          + "AND DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND T.CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND T.CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "<if test=\"combinedClassificationFilter != null\">"
          + "AND <foreach collection='combinedClassificationFilter' item='item' separator='OR'> "
          + "T.CLASSIFICATION_ID = #{item.taskClassificationId} "
          + "<if test=\"item.attachmentClassificationId != null\">"
          + "AND A.CLASSIFICATION_ID = #{item.attachmentClassificationId} "
          + "</if>"
          + "</foreach>"
          + "</if>"
          + "AND T.${timestamp} IS NOT NULL AND ( "
          + "<foreach collection='selectedItems' item='selectedItem' separator=' OR '>"
          + "#{selectedItem.key} = T.${groupedBy} AND "
          + "<if test=\"joinWithAttachments and combinedClassificationFilter == null\">"
          + "<if test='selectedItem.subKey != null'>"
          + "A.CLASSIFICATION_KEY = #{selectedItem.subKey} AND "
          + "</if>"
          + "</if>"
          + "<if test=\"_databaseId == 'db2'\">"
          + "#{selectedItem.upperAgeLimit} >= (DAYS(${timestamp}) - DAYS(CAST(#{now} as TIMESTAMP))) AND "
          + "#{selectedItem.lowerAgeLimit} &lt;= (DAYS(${timestamp}) - DAYS(CAST(#{now} as TIMESTAMP))) "
          + "</if> "
          + "<if test=\"_databaseId == 'h2'\">"
          + "#{selectedItem.upperAgeLimit} >= DATEDIFF('DAY', #{now}, ${timestamp}) AND "
          + "#{selectedItem.lowerAgeLimit} &lt;= DATEDIFF('DAY', #{now}, ${timestamp}) "
          + "</if> "
          + "<if test=\"_databaseId == 'postgres'\">"
          + "#{selectedItem.upperAgeLimit} >= DATE_PART('day', ${timestamp} - #{now} ) AND "
          + "#{selectedItem.lowerAgeLimit} &lt;= DATE_PART('day', ${timestamp} - #{now} ) "
          + "</if> "
          + "</foreach>) "
          + "</where>"
          + "<if test=\"_databaseId == 'db2'\">with UR </if> "
          + "</script>")
  List<String> getTaskIdsForSelectedItems(
      @Param("now") Instant now,
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report,
      @Param("combinedClassificationFilter")
          List<CombinedClassificationFilter> combinedClassificationFilter,
      @Param("groupedBy") String groupedBy,
      @Param("timestamp") TaskTimestamp timestamp,
      @Param("selectedItems") List<SelectedItem> selectedItems,
      @Param("joinWithAttachments") boolean joinWithAttachments);

  @Select(
      "<script>"
          + "SELECT WORKBASKET_KEY, STATE, COUNT(STATE) as COUNT "
          + "FROM TASK "
          + "<where>"
          + "<if test='domains != null'>"
          + "DOMAIN IN (<foreach collection='domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='states != null'>"
          + "AND STATE IN (<foreach collection='states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test='workbasketIds != null'>"
          + "AND WORKBASKET_ID IN (<foreach collection='workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test='priorityMinimum != null'>"
          + "AND priority >= #{priorityMinimum} "
          + "</if>"
          + "</where>"
          + "GROUP BY WORKBASKET_KEY, STATE"
          + "</script>")
  @Result(column = "WORKBASKET_KEY", property = "workbasketKey")
  @Result(column = "STATE", property = "state")
  @Result(column = "COUNT", property = "count")
  List<TaskQueryItem> getTasksCountByState(
      @Param("domains") List<String> domains,
      @Param("states") List<TaskState> states,
      @Param("workbasketIds") List<String> workbasketIds,
      @Param("priorityMinimum") Integer priorityMinimum);

  @Select(
      "<script>"
          + "SELECT DISTINCT ${customField} "
          + "FROM TASK T "
          + "<if test=\"combinedClassificationFilter != null\">"
          + "LEFT JOIN ATTACHMENT A ON T.ID = A.TASK_ID "
          + "</if>"
          + "<where>"
          + "<if test='report.workbasketIds != null'>"
          + "T.WORKBASKET_ID IN (<foreach collection='report.workbasketIds' item='workbasketId' separator=','>#{workbasketId}</foreach>) "
          + "</if>"
          + "<if test='report.states != null'>"
          + "AND T.STATE IN (<foreach collection='report.states' item='state' separator=','>#{state}</foreach>) "
          + "</if>"
          + "<if test='report.classificationCategory != null'>"
          + "AND T.CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test='report.domains != null'>"
          + "AND T.DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND T.CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND T.CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "<if test=\"combinedClassificationFilter != null\">"
          + "AND <foreach collection='combinedClassificationFilter' item='item' separator='OR'> "
          + "T.CLASSIFICATION_ID = #{item.taskClassificationId} "
          + "<if test=\"item.attachmentClassificationId != null\">"
          + "AND A.CLASSIFICATION_ID = #{item.attachmentClassificationId} "
          + "</if>"
          + "</foreach>"
          + "</if>"
          + "</where>"
          + "</script>")
  List<String> getCustomAttributeValuesForReport(
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report,
      @Param("combinedClassificationFilter")
          List<CombinedClassificationFilter> combinedClassificationFilter,
      @Param("customField") TaskCustomField taskCustomField);

  @Select(
      "<script>"
          + "SELECT A.AGE_IN_DAYS, A.ORG_LEVEL_1, A.ORG_LEVEL_2, A.ORG_LEVEL_3, A.ORG_LEVEL_4, "
          + "'${status}' AS STATUS, COUNT(A.AGE_IN_DAYS) AS COUNT FROM ("
          // This subquery prevents the repetition of the AGE_IN_DAYS column calculation
          // (like everywhere else in the Mappers...)in the group by clause.
          // DB2 is not able to reuse computed columns in the group by statement. Even if this adds
          // a little
          // overhead / complexity. It's worth the trade-off of not computing the AGE_IN_DAYS column
          // twice.
          + "SELECT W.ORG_LEVEL_1, W.ORG_LEVEL_2, W.ORG_LEVEL_3, W.ORG_LEVEL_4, "
          + "<if test=\"_databaseId == 'db2'\">(DAYS(T.${status}) - DAYS(CAST(#{now} as TIMESTAMP)))</if>"
          + "<if test=\"_databaseId == 'h2'\">DATEDIFF('DAY', #{now}, T.${status})</if>"
          + "<if test=\"_databaseId == 'postgres'\">DATE_PART('DAY', T.${status} - #{now})</if>"
          + " as AGE_IN_DAYS "
          + "FROM TASK AS T INNER JOIN WORKBASKET AS W ON T.WORKBASKET_KEY=W.KEY "
          + "<where>"
          + "<if test=\"status.name() == 'COMPLETED'\">"
          + "T.COMPLETED IS NOT NULL "
          + "</if>"
          + "<if test='report.classificationCategory != null'>"
          + "AND T.CLASSIFICATION_CATEGORY IN (<foreach collection='report.classificationCategory' item='category' separator=','>#{category}</foreach>) "
          + "</if>"
          + "<if test='report.classificationIds != null'>"
          + "AND T.CLASSIFICATION_ID IN (<foreach collection='report.classificationIds' item='classificationId' separator=','>#{classificationId}</foreach>) "
          + "</if>"
          + "<if test='report.excludedClassificationIds != null'>"
          + "AND T.CLASSIFICATION_ID NOT IN (<foreach collection='report.excludedClassificationIds' item='excludedClassificationId' separator=','>#{excludedClassificationId}</foreach>) "
          + "</if>"
          + "<if test='report.domains != null'>"
          + "AND T.DOMAIN IN (<foreach collection='report.domains' item='domain' separator=','>#{domain}</foreach>) "
          + "</if>"
          + "<if test='report.custom1In != null'>AND t.CUSTOM_1 IN(<foreach item='item' collection='report.custom1In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom1Like != null'>AND (<foreach item='item' collection='report.custom1Like' separator=' OR '>UPPER(t.CUSTOM_1) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom2In != null'>AND t.CUSTOM_2 IN(<foreach item='item' collection='report.custom2In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom2Like != null'>AND (<foreach item='item' collection='report.custom2Like' separator=' OR '>UPPER(t.CUSTOM_2) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom3In != null'>AND t.CUSTOM_3 IN(<foreach item='item' collection='report.custom3In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom3Like != null'>AND (<foreach item='item' collection='report.custom3Like' separator=' OR '>UPPER(t.CUSTOM_3) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom4In != null'>AND t.CUSTOM_4 IN(<foreach item='item' collection='report.custom4In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom4Like != null'>AND (<foreach item='item' collection='report.custom4Like' separator=' OR '>UPPER(t.CUSTOM_4) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom5In != null'>AND t.CUSTOM_5 IN(<foreach item='item' collection='report.custom5In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom5Like != null'>AND (<foreach item='item' collection='report.custom5Like' separator=' OR '>UPPER(t.CUSTOM_5) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom6In != null'>AND t.CUSTOM_6 IN(<foreach item='item' collection='report.custom6In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom6Like != null'>AND (<foreach item='item' collection='report.custom6Like' separator=' OR '>UPPER(t.CUSTOM_6) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom7In != null'>AND t.CUSTOM_7 IN(<foreach item='item' collection='report.custom7In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom7Like != null'>AND (<foreach item='item' collection='report.custom7Like' separator=' OR '>UPPER(t.CUSTOM_7) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom8In != null'>AND t.CUSTOM_8 IN(<foreach item='item' collection='report.custom8In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom8Like != null'>AND (<foreach item='item' collection='report.custom8Like' separator=' OR '>UPPER(t.CUSTOM_8) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom9In != null'>AND t.CUSTOM_9 IN(<foreach item='item' collection='report.custom9In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom9Like != null'>AND (<foreach item='item' collection='report.custom9Like' separator=' OR '>UPPER(t.CUSTOM_9) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom10In != null'>AND t.CUSTOM_10 IN(<foreach item='item' collection='report.custom10In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom10Like != null'>AND (<foreach item='item' collection='report.custom10Like' separator=' OR '>UPPER(t.CUSTOM_10) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom11In != null'>AND t.CUSTOM_11 IN(<foreach item='item' collection='report.custom11In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom11Like != null'>AND (<foreach item='item' collection='report.custom11Like' separator=' OR '>UPPER(t.CUSTOM_11) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom12In != null'>AND t.CUSTOM_12 IN(<foreach item='item' collection='report.custom12In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom12Like != null'>AND (<foreach item='item' collection='report.custom12Like' separator=' OR '>UPPER(t.CUSTOM_12) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom13In != null'>AND t.CUSTOM_13 IN(<foreach item='item' collection='report.custom13In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom13Like != null'>AND (<foreach item='item' collection='report.custom13Like' separator=' OR '>UPPER(t.CUSTOM_13) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom14In != null'>AND t.CUSTOM_14 IN(<foreach item='item' collection='report.custom14In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom14Like != null'>AND (<foreach item='item' collection='report.custom14Like' separator=' OR '>UPPER(t.CUSTOM_14) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom15In != null'>AND t.CUSTOM_15 IN(<foreach item='item' collection='report.custom15In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom15Like != null'>AND (<foreach item='item' collection='report.custom15Like' separator=' OR '>UPPER(t.CUSTOM_15) LIKE #{item}</foreach>)</if> "
          + "<if test='report.custom16In != null'>AND t.CUSTOM_16 IN(<foreach item='item' collection='report.custom16In' separator=',' >#{item}</foreach>)</if> "
          + "<if test='report.custom16Like != null'>AND (<foreach item='item' collection='report.custom16Like' separator=' OR '>UPPER(t.CUSTOM_16) LIKE #{item}</foreach>)</if> "
          + "</where>"
          + ") AS A "
          + "GROUP BY A.AGE_IN_DAYS, A.ORG_LEVEL_1, A.ORG_LEVEL_2, A.ORG_LEVEL_3, A.ORG_LEVEL_4 "
          + "</script>")
  @Result(column = "STATUS", property = "status")
  @Result(column = "AGE_IN_DAYS", property = "ageInDays")
  @Result(column = "COUNT", property = "count")
  @Result(column = "ORG_LEVEL_1", property = "orgLevel1")
  @Result(column = "ORG_LEVEL_2", property = "orgLevel2")
  @Result(column = "ORG_LEVEL_3", property = "orgLevel3")
  @Result(column = "ORG_LEVEL_4", property = "orgLevel4")
  List<TimestampQueryItem> getTasksCountForStatusGroupedByOrgLevel(
      @Param("now") Instant now,
      @Param("status") TaskTimestamp status,
      @Param("report") TimeIntervalReportBuilder<?, ?, ?> report);
}
