-- this script updates the TASKANA_HISTORY_EVENT table.

SET search_path %schemaName%;

ALTER TABLE TASK_HISTORY_EVENT ALTER COLUMN CUSTOM_1 TYPE VARCHAR(255), ALTER COLUMN CUSTOM_2 TYPE VARCHAR(255), ALTER COLUMN CUSTOM_3 TYPE VARCHAR(255), ALTER COLUMN CUSTOM_4 TYPE VARCHAR(255);
