-- this script updates the database schema from TASKANA version 8.2.0 to KADAI version 9.0.0.
SET SCHEMA %schemaName%;

RENAME TABLE TASKANA_SCHEMA_VERSION TO KADAI_SCHEMA_VERSION;

DROP SEQUENCE TASKANA_SCHEMA_VERSION_ID_SEQ;
CREATE SEQUENCE KADAI_SCHEMA_VERSION_ID_SEQ
    MINVALUE 1
    START WITH 1000
    INCREMENT BY 1 CACHE 10;

INSERT INTO KADAI_SCHEMA_VERSION (ID, VERSION, CREATED)
VALUES (KADAI_SCHEMA_VERSION_ID_SEQ.NEXTVAL, '9.0.0', CURRENT_TIMESTAMP);
