-- this script updates the TASKANA database schema from version 7.0.0 to version 7.0.1.

INSERT INTO TASKANA_SCHEMA_VERSION (ID, VERSION, CREATED)
VALUES (nextval('TASKANA_SCHEMA_VERSION_ID_SEQ'), '7.0.1', CURRENT_TIMESTAMP);

ALTER TABLE TASK
    ADD COLUMN NUMBER_OF_COMMENTS INT DEFAULT 0;

UPDATE Task t
SET NUMBER_OF_COMMENTS = (
	SELECT COUNT(*)
	FROM TASK_COMMENT tc
	WHERE tc.TASK_ID = t.ID
);
