-- the order is important!
DELETE FROM TASKANA.ATTACHMENT;
DELETE FROM TASKANA.TASK;
DELETE FROM TASKANA.WORKBASKET_ACCESS_LIST;
DELETE FROM TASKANA.WORKBASKET;
DELETE FROM TASKANA.DISTRIBUTION_TARGETS;
DELETE FROM TASKANA.CLASSIFICATION;
DELETE FROM TASKANA.OBJECT_REFERENCE;
-- do not clean JOB table
-- DELETE FROM TASKANA.SCHEDULED_JOB;
COMMIT;
