-- the order is important!
DELETE FROM ATTACHMENT;
DELETE FROM TASK;
DELETE FROM WORKBASKET_ACCESS_LIST;
DELETE FROM WORKBASKET;
DELETE FROM DISTRIBUTION_TARGETS;
DELETE FROM CLASSIFICATION;
DELETE FROM OBJECT_REFERENCE;
DELETE FROM HISTORY_EVENTS;
-- do not clean JOB table
-- DELETE FROM SCHEDULED_JOB;
COMMIT;
