export enum WorkbasketPermission {
  READ = 'READ',
  OPEN = 'OPEN',
  APPEND = 'APPEND',
  TRANSFER = 'TRANSFER',
  DISTRIBUTE = 'DISTRIBUTE',
  CUSTOM_1 = 'CUSTOM_1',
  CUSTOM_2 = 'CUSTOM_2',
  CUSTOM_3 = 'CUSTOM_3',
  CUSTOM_4 = 'CUSTOM_4',
  CUSTOM_5 = 'CUSTOM_5',
  CUSTOM_6 = 'CUSTOM_6',
  CUSTOM_7 = 'CUSTOM_7',
  CUSTOM_8 = 'CUSTOM_8',
  CUSTOM_9 = 'CUSTOM_9',
  CUSTOM_10 = 'CUSTOM_10',
  CUSTOM_11 = 'CUSTOM_11',
  CUSTOM_12 = 'CUSTOM_12'
}
