export interface WorkbasketSummary {
  workbasketId?: string,
  key?: string,
  name?: string,
  description?: string,
  owner?: string,
  modified?: string,
  domain?: string,
  type: string,
  orgLevel1?: string,
  orgLevel2?: string,
  orgLevel3?: string,
  orgLevel4?: string,
  markedForDeletion?: boolean,
}
