CREATE TABLE IF NOT EXISTS TASK( 
	ID varchar(36) NOT NULL,
	TENANT_ID varchar(36) NULL,
	CREATED TIMESTAMP NULL,
	CLAIMED TIMESTAMP NULL,
	COMPLETED TIMESTAMP NULL,
	MODIFIED TIMESTAMP NULL,
	PLANNED TIMESTAMP NULL,
	DUE TIMESTAMP NULL,
	NAME varchar(1024) NULL,
	DESCRIPTION varchar(4096) NULL,
	PRIORITY INT NULL,
	STATE varchar(20) NULL,
	TYPE varchar(255) NULL,
	WORKBASKETID varchar(36) NULL,
	OWNER varchar(255) NULL,
	PRIMARY_OBJ_REF_ID varchar(36) NULL,
	IS_READ bit NOT NULL,
	IS_TRANSFERRED bit NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS WORKBASKET(
	ID varchar(36) NOT NULL,
	TENANT_ID varchar(36) NULL,
	CREATED TIMESTAMP NULL,
	MODIFIED TIMESTAMP NULL,
	NAME varchar(255) NULL,
	DESCRIPTION varchar(255) NULL,
	OWNER varchar(255) NULL,
	PRIMARY KEY (ID),
	CONSTRAINT UC_NAME UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS DISTRIBUTION_TARGETS(
	SOURCE_ID varchar(36) NOT NULL,
	TARGET_ID varchar(36) NOT NULL,
	PRIMARY KEY (SOURCE_ID, TARGET_ID)
);

CREATE TABLE IF NOT EXISTS CLASSIFICATION(
	ID varchar(36) NOT NULL,
	TENANT_ID varchar(36) NULL,
	PARENT_CLASSIFICATION_ID varchar(255),
	CATEGORY varchar(255),
	TYPE varchar(255),
	CREATED DATE NULL,
	MODIFIED DATE NULL,
	NAME varchar(255) NULL,
	DESCRIPTION varchar(255) NULL,
	PRIORITY INT NULL,
	SERVICE_LEVEL varchar(255) NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS WORKBASKET_ACCESS_LIST(
	ID varchar(36) NOT NULL,
	WORKBASKET_ID varchar(36) NOT NULL,
	USER_ID varchar(255) NULL,
	GROUP_ID varchar(255) NULL,
	READ bit NOT NULL,
	OPEN bit NOT NULL,
	APPEND bit NOT NULL,
	TRANSFER bit NOT NULL,
	DISTRIBUTE bit NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS OBJECT_REFERENCE(
	ID varchar(36) NOT NULL,
	TENANT_ID varchar(36) NULL,
	COMPANY varchar(32) NOT NULL,
	SYSTEM varchar(32) NOT NULL,
	SYSTEM_INSTANCE varchar(32) NOT NULL,
	TYPE varchar(32) NOT NULL,
	VALUE varchar(128) NOT NULL
);
