CREATE TABLE TASKANA_SCHEMA_VERSION(
	ID VARCHAR(36) NOT NULL,
	VERSION VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);
INSERT INTO TASKANA_SCHEMA_VERSION VALUES ('1', '0.0.1');

CREATE TABLE TASK( 
	ID VARCHAR(36) NOT NULL,
	TENANT_ID VARCHAR(36) NULL,
	CREATED TIMESTAMP NULL,
	CLAIMED TIMESTAMP NULL,
	COMPLETED TIMESTAMP NULL,
	MODIFIED TIMESTAMP NULL,
	PLANNED TIMESTAMP NULL,
	DUE TIMESTAMP NULL,
	NAME VARCHAR(1024) NULL,
	DESCRIPTION VARCHAR(4096) NULL,
	PRIORITY INT NULL,
	STATE VARCHAR(20) NULL,
	TYPE VARCHAR(255) NULL,
	WORKBASKETID VARCHAR(36) NULL,
	OWNER VARCHAR(255) NULL,
	PRIMARY_OBJ_REF_ID varchar(36) NULL,
	IS_READ BOOLEAN NOT NULL,
	IS_TRANSFERRED BOOLEAN NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE WORKBASKET(
	ID VARCHAR(36) NOT NULL,
	TENANT_ID VARCHAR(36) NULL,
	CREATED TIMESTAMP NULL,
	MODIFIED TIMESTAMP NULL,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NULL,
	OWNER VARCHAR(255) NULL,
	PRIMARY KEY (ID),
	CONSTRAINT UC_NAME UNIQUE (NAME)
);

CREATE TABLE DISTRIBUTION_TARGETS(
	SOURCE_ID VARCHAR(36) NOT NULL,
	TARGET_ID VARCHAR(36) NOT NULL,
	PRIMARY KEY (SOURCE_ID, TARGET_ID)
);

CREATE TABLE CLASSIFICATION(
	ID VARCHAR(36) NOT NULL,
	TENANT_ID VARCHAR(36) NULL,
	PARENT_CLASSIFICATION_ID VARCHAR(255),
	CATEGORY VARCHAR(255),
    TYPE VARCHAR(255),
	CREATED DATE NULL,
	MODIFIED DATE NULL,
	NAME VARCHAR(255) NULL,
	DESCRIPTION VARCHAR(255) NULL,
	PRIORITY INT NULL,
	SERVICE_LEVEL VARCHAR(255) NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE WORKBASKET_ACCESS_LIST(
	ID VARCHAR(36) NOT NULL,
	WORKBASKET_ID VARCHAR(36) NOT NULL,
	USER_ID VARCHAR(255) NULL,
	GROUP_ID VARCHAR(255) NULL,
	READ BOOLEAN NOT NULL,
	OPEN BOOLEAN NOT NULL,
	APPEND BOOLEAN NOT NULL,
	TRANSFER BOOLEAN NOT NULL,
	DISTRIBUTE BOOLEAN NOT NULL,
	PRIMARY KEY (ID)
);
