DROP TABLE IF EXISTS TASKANA_SCHEMA_VERSION;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS WORKBASKET;
DROP TABLE IF EXISTS DISTRIBUTION_TARGETS;
DROP TABLE IF EXISTS CLASSIFICATION;
DROP TABLE IF EXISTS WORKBASKET_ACCESS_LIST;
DROP TABLE IF EXISTS OBJECT_REFERENCE;
DROP TABLE IF EXISTS ATTACHMENT;
COMMIT;
